- name: create redis dir
  file:
    path: "{{ redis_dir }}"
    state: directory
- name: create redis data dir
  file:
    path: "{{ redis_dir }}/data"
    state: directory
    mode: 0777
- name: copy docker-compose file for redis
  template:
    src: docker-compose.yml.j2
    dest: "{{ redis_dir }}/docker-compose.yml"
  register: compose_file
- name: pull images
  shell: "docker-compose -f {{ redis_dir }}/docker-compose.yml pull"
  register: docker_pull
- name: remove old container
  shell: "docker-compose -f {{ redis_dir }}/docker-compose.yml down"
  ignore_errors: yes
- name: launch container
  shell: "docker-compose -f {{ redis_dir }}/docker-compose.yml up -d"