---
- name: Install docker
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - docker
- name: Enable and restart docker in systemd
  systemd:
    name: docker
    enabled: yes
    state: restarted
- name: Install Docker Compose.
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64'
    dest: '/bin/docker-compose'
    mode: 0755
