---
- name: install keepalived
  apt:
    name: ["keepalived"]
    state: present
  become: yes

- name: copy check_harbor.sh
  copy:
    src: check_harbor.sh
    dest: /opt/check_harbor.sh
    mode: 0764
  register: check

- name: copy keepalivednotify.sh
  copy:
    src: keepalivednotify.sh
    dest: /opt/keepalivednotify.sh
    mode: 0764
  register: notify

- name: set up keepalived config
  template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
  register: config

- name: restart keepalived
  systemd:
    name: keepalived
    enabled: yes
    state: restarted
  when: notify.changed or check.changed or config.changed
