- name: harbor server.
  hosts: harbor
  become: True
  become_method: sudo
  roles:
    - { role: pre-install/docker, tags: ["docker"] }
    - { role: postgresql, tags: ["postgresql"] }
- name: harbor server.
  hosts: harbor
  become: True
  become_method: sudo
#   serial: 1
  roles:
    - { role: harbor, tags: ["harbor"] }
    - { role: keepalived, tags: ["keepalived"] }
    - { role: prometheus, tags: ["prometheus"] }
