- name: harbor server.
  hosts: harbor
  become: True
  become_method: sudo
  # environment:
  #   HARBOR_DB_USER: "{{ harbor_db_user }}"
  #   HARBOR_DB_PASSWORD: "{{ harbor_db_password }}"
  #   HARBOR_DB_ROOT_PASSWORD: "{{ harbor_db_root_password }}"
  roles:
    - { role: pre-install/docker, tags: ["docker"] }
    - { role: postgresql, tags: ["postgresql"] }
    - { role: harbor, tags: ["harbor"] }
    - { role: prometheus, tags: ["prometheus"] }
