- name: install postgresql-client
  apt:
    name: ["postgresql-client"]
    state: present
  become: yes
- name: create postgresql dir
  file:
    path: "{{ db_dir }}"
    state: directory
- name: create postgresql dir
  file:
    path: "{{ db_dir }}/config"
    state: directory
- name: create postgresql data dir
  file:
    path: "{{ db_data_dir }}"
    state: directory
    mode: 0777
- name: copy docker-compose file for postgresql
  template:
    src: docker-compose.yml.j2
    dest: "{{ db_dir }}/docker-compose.yml"
  register: compose_file
- name: replace postgresql env file
  template:
    src: "postgresql/{{server_role}}-env.j2"
    dest: "{{ db_dir }}/config/env"
    backup: yes
  register: db_env

# - name: pull images
#   shell: "docker-compose -f {{ db_dir }}/docker-compose.yml pull"
#   register: docker_pull

- name: pull an image
  docker_image:
    name: "{{ postgresql_image }}"

- name: remove old container
  shell: "docker-compose -f {{ db_dir }}/docker-compose.yml down"
  ignore_errors: yes
  when: db_env.changed

- name: launch container
  shell: "docker-compose -f {{ db_dir }}/docker-compose.yml up -d"
  when: db_env.changed

- debug:
    msg: "{{groups['harbor'][0]}}"

# For Clair
- name: Init Clair DB | check database exist or not
  shell: "docker exec -t harbor-db psql -U postgres -c \"SELECT 1 FROM pg_database WHERE datname = 'clair'\" | grep -q 1 "
  register: clair_db
  until: clair_db.rc == 0
  retries: 6
  delay: 5
  ignore_errors: yes
  when: groups['harbor'][0] == ansible_default_ipv4.address

- name: Init Clair DB | debug clair_db
  debug:
    msg: "{{clair_db}}"
  when: groups['harbor'][0] == ansible_default_ipv4.address and clair_db.failed

- name: Init Clair DB | create database
  shell: "docker exec -t harbor-db psql -U postgres -c \"create database clair;\""
  register: create_clair_db
  when: groups['harbor'][0] == ansible_default_ipv4.address and clair_db.failed

- name: Init Clair DB | create user
  shell: "docker exec -t harbor-db psql -U postgres -c \"create user {{ clair_db_user }} with encrypted password '{{ clair_db_password }}';\""
  register: create_clair_user
  when: groups['harbor'][0] == ansible_default_ipv4.address and create_clair_db.changed

- name: Init Clair DB | create user
  shell: "docker exec -t harbor-db psql -U postgres -c \"grant all privileges on database clair to {{ clair_db_user }};\""
  when: groups['harbor'][0] == ansible_default_ipv4.address and create_clair_user.changed



# For Notary
- name: Init Notary DB | check database exist or not
  shell: "docker exec -t harbor-db psql -U postgres -c \"SELECT 1 FROM pg_database WHERE datname = 'notarysigner'\" | grep -q 1 "
  register: notary_db
  until: notary_db.rc == 0
  retries: 6
  delay: 5
  ignore_errors: yes
  when: groups['harbor'][0] == ansible_default_ipv4.address

- name: Init Notary DB | debug notary_db
  debug:
    msg: "{{notary_db}}"
  when: groups['harbor'][0] == ansible_default_ipv4.address and notary_db.failed

- name: Init Notary DB | create database
  shell: "docker exec -t harbor-db psql -U postgres -c \"create database notarysigner;\""
  register: create_notary_db
  when: groups['harbor'][0] == ansible_default_ipv4.address and notary_db.failed

- name: Init Notary DB | create user
  shell: "docker exec -t harbor-db psql -U postgres -c \"create user {{ notary_signer_db_user }} with encrypted password '{{ notary_signer_db_password }}';\""
  register: create_notary_user
  when: groups['harbor'][0] == ansible_default_ipv4.address and create_notary_db.changed

- name: Init Notary DB | create user
  shell: "docker exec -t harbor-db psql -U postgres -c \"grant all privileges on database notarysigner to {{ notary_signer_db_user }};\""
  when: groups['harbor'][0] == ansible_default_ipv4.address and create_notary_user.changed
