- name: install postgresql-client
  apt:
    name: ["postgresql-client"]
    state: present
  become: yes
- name: create postgresql dir
  file:
    path: "{{ db_dir }}"
    state: directory
- name: create postgresql dir
  file:
    path: "{{ db_dir }}/config"
    state: directory
- name: create postgresql data dir
  file:
    path: "{{ db_data_dir }}"
    state: directory
    mode: 0777
- name: copy docker-compose file for postgresql
  template:
    src: docker-compose.yml.j2
    dest: "{{ db_dir }}/docker-compose.yml"
  register: compose_file
- name: replace postgresql env file
  template:
    src: "postgresql/{{server_role}}-env.j2"
    dest: "{{ db_dir }}/config/env"
    backup: yes
  register: db_env
# - name: init scripts
#   template:
#     src: db_init.sql.j2
#     dest: "{{ db_dir }}/config/db_init.sql"
#     mode: 0755
- name: pull images
  shell: "docker-compose -f {{ db_dir }}/docker-compose.yml pull"
  register: docker_pull
- name: remove old container
  shell: "docker-compose -f {{ db_dir }}/docker-compose.yml down"
  ignore_errors: yes

- name: launch container
  shell: "docker-compose -f {{ db_dir }}/docker-compose.yml up -d"

- name: Init Clair DB | check database exist or not
  shell: "docker exec -t postgresql psql -U postgres -c \"SELECT 1 FROM pg_database WHERE datname = 'clair'\" | grep -q 1 "
  register: clair_db
  until: clair_db.rc == 0
  retries: 12
  delay: 5
  ignore_errors: yes

- name: Init Clair DB | debug clair_db
  debug:
    msg: "{{clair_db}}"
  when: clair_db.failed

- name: Init Clair DB | create database
  shell: "docker exec -t postgresql psql -U postgres -c \"create database clair;\""
  register: create_clair_db
  when: clair_db.failed

- name: Init Clair DB | create user
  shell: "docker exec -t postgresql psql -U postgres -c \"create user {{ clair_db_user }} with encrypted password '{{ clair_db_password }}';\""
  register: create_clair_user
  when: create_clair_db.changed

- name: Init Clair DB | create user
  shell: "docker exec -t postgresql psql -U postgres -c \"grant all privileges on database clair to {{ clair_db_user }};\""
  when: create_clair_user.changed
